// <auto-generated />
using DatingWebb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatingWebb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415122902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DatingWebb.Models.UserMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserMatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            Bio = "",
                            ImageUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
                            Name = "Sarah Thorne",
                            Status = "Đã tương hợp"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Bio = "",
                            ImageUrl = "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
                            Name = "Julianne",
                            Status = "Đã tương hợp"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Bio = "",
                            ImageUrl = "https://images.unsplash.com/photo-1531746020798-e7953e3e8c5c",
                            Name = "Emily",
                            Status = "Vừa tương hợp"
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Bio = "",
                            ImageUrl = "https://images.unsplash.com/photo-1517841905240-472988babdf9",
                            Name = "Chloe",
                            Status = "Đã tương hợp"
                        },
                        new
                        {
                            Id = 5,
                            Age = 36,
                            Bio = "",
                            ImageUrl = "https://vcdn1-giaitri.vnecdn.net/2023/01/18/lee-min-ho-1-1674015655-2365-1674015843.jpg",
                            Name = "Min Ho",
                            Status = "Vừa tương hợp"
                        },
                        new
                        {
                            Id = 6,
                            Age = 28,
                            Bio = "",
                            ImageUrl = "https://i.pinimg.com/originals/8d/3f/0a/8d3f0a1496677f547c6676059d435f11.jpg",
                            Name = "Taehyung",
                            Status = "Đã tương hợp"
                        },
                        new
                        {
                            Id = 7,
                            Age = 38,
                            Bio = "",
                            ImageUrl = "https://i.pinimg.com/736x/8f/3e/2a/8f3e2a738c8247071f0c23946258f4a3.jpg",
                            Name = "Joong Ki",
                            Status = "Đã tương hợp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
